SELECT *
FROM Customer

--1: Total revenue generated by male v/s female customers
SELECT gender, sum(purchase_amount) as revenue
FROM Customer
GROUP BY gender

--2: Customers used discount but still spent more than average purchase amount
SELECT customer_id,purchase_amount
FROM Customer
WHERE discount_applied='Yes' AND purchase_amount>=(SELECT AVG(purchase_amount) FROM Customer)

--3: Top 5 products with highest average review rating
SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) rating
FROM Customer
GROUP BY item_purchased
ORDER BY rating DESC
LIMIT 5

--4: Compare the average purchase with standard and express shippin
SELECT shipping_type, ROUND(AVG(purchase_amount::numeric),2) Average
FROM Customer
GROUP BY shipping_type
HAVING shipping_type='Express' OR shipping_type='Standard'

--5 Do subscribed customers spend more? Compare average spent and total revenue
--between subscribers and non-subscribers
SELECT subscription_status, ROUND(AVG(purchase_amount::numeric),2) Average_purchase, ROUND(SUM(purchase_amount::numeric),2) total_revenue
FROM Customer
GROUP BY subscription_status

--6: Top 5 producs with highest percentage of purchases with discounts
SELECT item_purchased, ROUND(100*SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) percentage
FROM Customer
GROUP BY item_purchased
ORDER BY percentage DESC
LIMIT 5;

--7: Segment customers into New, Returning, Loyal based on their total number of 
-- previous purchases, show the count of each segment
WITH customer_type AS(
	SELECT customer_id, previous_purchases, CASE WHEN previous_purchases=1 THEN 'New'
												 WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
												 ELSE 'Loyal'
												 END AS cust_type
	FROM Customer)

SELECT cust_type, COUNT(cust_type)
FROM customer_type
GROUP BY cust_type

--8: What are the top 3 most purchased products within each category
WITH cat AS(
	SELECT item_purchased, category, count(customer_id) total, RANK() OVER(PARTITION BY category ORDER BY count(customer_id)) top3
	FROM Customer
	GROUP BY item_purchased,category
)

SELECT item_purchased, category, total
FROM cat
WHERE top3<=3

--9: Will repeat buyers(purchase more than 5 times) subscribe?
SELECT subscription_status, count(customer_id)
FROM Customer
WHERE previous_purchases>5
GROUP BY subscription_status

--10 Revenue contribution of each group:
SELECT age_group, SUM(purchase_amount) total_revenue
FROM Customer
GROUP BY age_group
ORDER BY total_revenue DESC
